In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

# create a 1d array
# arr1=np.array([1,2,3,4,5])
# print(arr1)
# print(type(arr1))
# print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) 
# Basically 1 row and 5 columns

NameError: name 'np' is not defined

In [9]:
arr2=np.array([[1,2,3,4,5],[1,3,5,7,9],[1,2,3,4,5]])
arr2.shape
print(arr2)

[[1 2 3 4 5]
 [1 3 5 7 9]
 [1 2 3 4 5]]


In [13]:
np.arange(0,10,2)
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])